### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by weiweihuanghuang** [jenskutilek/nibLib#2]
GA 3.2 (3241)
macOS Big Sur, 11.7.10 (20G1427)
nibLib v1.2.0
```
A plugin caused a crash

The Plugin NibSimulator.glyphsReporter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/plugins.py", line 1395, in raiseException_

  File "GlyphsApp/GlyphsApp/plugins.py", line 1211, in drawBackgroundForLayer_options_

  File "plugin.py", line 53, in background
    self.w.draw_preview_glyph(scale=self.getScale())

  File "glyphs.py", line 72, in draw_preview_glyph
    self.guide_layer.draw(p)

  File "GlyphsApp/GlyphsApp/__init__.py", line 9341, in DrawLayerWithPen

  File "GlyphsApp/GlyphsApp/__init__.py", line 10482, in DrawPathWithPen

  File "basePen.py", line 305, in curveTo
    self._curveToOne(*points)

  File "superellipseNibPen.py", line 127, in _curveToOne
    points = getPointsFromCurve((self._currentPoint, t1, t2, t3), 5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "geometry.py", line 24, in getPointsFromCurve
    length = calcCubicArcLength(p[0], p[1], p[2], p[3])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "bezierTools.py", line 70, in calcCubicArcLength
    return calcCubicArcLengthC(
           ^^^^^^^^^^^^^^^^^^^^

  File "bezierTools.py", line 126, in calcCubicArcLengthC
    return _calcCubicArcLengthCRecurse(mult, pt1, pt2, pt3, pt4)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "bezierTools.py", line 99, in _calcCubicArcLengthCRecurse
    return _calcCubicArcLengthCRecurse(mult, *one) + _calcCubicArcLengthCRecurse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "bezierTools.py", line 99, in _calcCubicArcLengthCRecurse
    return _calcCubicArcLengthCRecurse(mult, *one) + _calcCubicArcLengthCRecurse(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "bezierTools.py", line 99, in _calcCubicArcLengthCRecurse
    return _calcCubicArcLengthCRecurse(mult, *one) + _calcCubicArcLengthCRecurse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  [Previous line repeated 986 more times]

  File "bezierTools.py", line 93, in _calcCubicArcLengthCRecurse
    arch = abs(p0 - p3)
           ^^^^^^^^^^^^

RecursionError: maximum recursion depth exceeded while calling a Python object

App:3.2-3241 Plugin:1.2-3 System:11.7.10
```

**Comment by weiweihuanghuang** [comment]
Ah I realised it takes the background as the stroke! I had a very complicate drawing back there.
